host:
 domain: a220d924eef9c4ac78f3db3f7d17b1fd-1566615617.us-west-2.elb.amazonaws.com

# Alerting config
prometheus:
 serverFiles:
  alerting_rules.yml:
   groups:
    - name: StatusError
      rules:
        - alert: AppDown
          expr: probe_success == 0
          for: 10s
          labels:
            severity: "critical"
          annotations:
            summary: "App is not showing a 200 response code"
        - alert: Too many 4xx errors
          expr: sum_over_time(nginx_http_response_count_total{status=~'4.*'}[1h]) > 100
          labels:
            severity: page
          annotations:
            summary: Too many 4xx Errors found in App for 1 hour
        - alert: Too many 5xx errors
          expr: sum_over_time(nginx_http_response_count_total{status=~'5.*'}[5m]) > 50
          labels:
            severity: page
          annotations:
            summary: Too many 4xx Errors found in App for 5 minutes

# Config for prometheus to probe our domain name through blackbox exporter
 extraScrapeConfigs: |
   - job_name: 'prometheus-blackbox-exporter'
     metrics_path: /probe
     params:
       module: [http_2xx]
     static_configs:
       - targets:
         - a220d924eef9c4ac78f3db3f7d17b1fd-1566615617.us-west-2.elb.amazonaws.com
     relabel_configs:
       - source_labels: [__address__]
         target_label: __param_target
       - source_labels: [__param_target]
         target_label: instance
       - target_label: __address__
         replacement: {{ .Release.Name }}-prometheus-blackbox-exporter:9115
